### ISSUE TITLE
Dynamic modules connection

### ISSUE THREAD

**Issue by Shekhovtsovy** [yii2tech/config#11]
Can I add new modules dynamicly, but not only parametrs of nested modules?

For example:        
```
 'NewModules' => [
                     'Path' => 'modules',
                     'Label' => new Modules',
                 ],
```
and db row
id: `NewModules`
'value: `['user'=>'path/to/Module']`

**Comment by klimov-paul** [comment]
It is impossible to manipulate entities, which do not exist in current application. Dynamic componenst or modules can not be added.
