### ISSUE TITLE
Allow ingore invalid config key

### ISSUE THREAD

**Issue by klimov-paul** [yii2tech/config#13]
In case structure of the object, which is under configuration, changes, existing configuration saved in DB may become invalid for it.
For example: in case some public field of the configured class is renamed, attempt to apply already saved configuration may end with exception 'Setting unknown property: renamedProperty'.
There should be an option, which allows automatic shutdown of such exceptions.

**Comment by klimov-paul** [comment]
Resolved by commit 6f9772ffab5ac6a3ddce4a28f36b6bbecf0dc7cc

**Comment by MaksBrainiac** [comment]
When I use yii2tech\config\Manager in app components with storage-class is yii2tech\config\StorageDb
and some item are deleted from "items" I receive InvalidParamException with message: "Unknown config item" in component bootstrap:

> public function bootstrap($app)
>     {
>         try {
>             $this->configure($app);
>         } catch (\Exception $exception) {
>            // ----------> InvalidParamException  <------------ //
>            // ----------> Unknown config item "" <------------ //
>             // fetching config from storage like database may fail at initial point, like before DB migrations applied
>             Yii::warning($exception->getMessage(), __METHOD__);
>         }
>     }

 and nothing is applied to $app


>     public function configure($module, $config = null)
>     {
>         if ($config === null) {
>             $config = $this->fetchConfig();   //  <----- Exception is here
>         }
> 
>         if (!$module instanceof Module) {
>             foreach ($config as $key => $value) {
>                 $this->configureObjectProperty($module, $key, $value);
>             }
>             return;
>         }
