### ISSUE TITLE
Support detect path via id if property `source` is set.

### ISSUE THREAD

**Issue by vuongminh-xx** [yii2tech/config#14]
In version 1.0.4, We can configure an object is not instance of `Module` when config `source` property, i suggest in method `composeDefaultPath` of `Item` class if `source` property is set and value isn't an instance of `Module`, it should be return `id` value. [#L195](https://github.com/yii2tech/config/blob/master/src/Item.php#L195)

**Comment by klimov-paul** [comment]
Rejected: value path is composed before 'object to be configured' can be determined. Thus there is no way of telling whether it is instance of `Module` or not.
You should specify item path in array format for standalone configuration setup.
