### ISSUE TITLE
Update process delete old item data perfomace in StorageActiveRecord

### ISSUE THREAD

**Issue by vuongminh-xx** [yii2tech/config#16]
In [L70](https://github.com/yii2tech/config/blob/master/src/StorageActiveRecord.php#L70) of StorageActiveRecord will execute many delete queries, we should change it to:

```php

$ids = \yii\helpers\ArrayHelper::getColumn($existingRecords, 'id');
$activeRecordClass::deleteAll(array_merge($filterAttributes, ['id' => $ids]));

```

It only call one time.

**Comment by klimov-paul** [comment]
Rejected. Such solution will eliminate the 'beforeDelete' event call.
