### ISSUE TITLE
Store items in serializable format

### ISSUE THREAD

**Issue by ARHImed82** [yii2tech/config#17]
Some config items have multiple values in array format. As I use `StorageActiveRecord` storage class, so in ActiveRecord class I use `beforeSave()` and `afterFind()` methods for serialize and unserialize values respectively. Saving are good, but restoring config value gives a serializing string.
I think it will be very useful feature for such situations.

**Comment by klimov-paul** [comment]
Resolved by commit 0db748dd2dfb5ec8d09f0a8b711a9f845922f40a
