### ISSUE TITLE
FilterCondition for StoragePhp

### ISSUE THREAD

**Issue by dbd5** [yii2tech/config#20]
@klimov-paul 

I have looked at the documentation and the source but I have not figured out a suitable way to make a variation for StoragePhp to achieve something similar to the filter condition for StorageDb.

In my use case, an init script at bootstrap determines certain run parameters from config settings after looking at the Url and returns a value called ExecutionMode that can be in the range 1,2,3. 

I would like a way to use the ExecutionMode parameter as a filter to decide which of the possible configuration arrays to load with StoragePhp and apply to the application.

Any suggestions or am I missing something?

Thanks as usual for a great module!

Adam

**Comment by klimov-paul** [comment]
`StorageFilterTrait::$filter` never was intended to be used in this way.
In your case you should re-set the storage or create it according to the environement condition.
You may setup an application bootstrap function to re-configure `Manager` instance, use DI features or create a separated storage.
