### ISSUE TITLE
Category as additional property of yii2tech\config\Item

### ISSUE THREAD

**Issue by maxodrom** [yii2tech/config#22]
Нельзя ли добавить некоторое доп. property с названием category для конфигурирования yii2tech\config\Item и указания на категорию, к которой Item относится? 
Это было бы полезным и актуальным при группировке Items в пользовательском интерфейсе, которые отражает возможные опции конфигурации и работает с ними. По таким категориям удобно разбивать отдельные конфигурационные элементы, чтобы позиционировать их как группы в пользовательском интерфейсе.
Thank you.

**Comment by klimov-paul** [comment]
You can use [Item::$inputOptions](https://github.com/yii2tech/config/blob/master/src/Item.php#L61-L64) for this purpose, adding key 'category' to it.

```php
[
    'components' => [
        'configManager' => [
            'class' => 'yii2tech\config\Manager',
            'items' => [
                'appName' => [
                    'path' => 'name',
                    // ...
                    'inputOptions' => [
                        'category' => 'category-1'
                    ],
                ],
                ...
            ],
        ],
        ...
    ],
];
```

You can also create your own `Item` class, adding extra fields or properties to it and use it instead of standard one:

```php
[
    'components' => [
        'configManager' => [
            'class' => 'yii2tech\config\Manager',
            'items' => [
                'appName' => [
                    'class' => MyItem::class,
                    'path' => 'name',
                    'category' => 'category-1'
                    // ...
                ],
                ...
            ],
        ],
        ...
    ],
];
```
