### ISSUE TITLE
Modified histories and user specified config

### ISSUE THREAD

**Issue by sheillendra** [yii2tech/config#6]
Thank you so much this extension is very helpful.

I have some enhancement, preferably in table added created_at column, created_by, updated_at and updated_by, because config can be changed by a different user.

Others, such as the language config it sometimes depends to a user id or other specific categories, how to implement it with this extension ?.

thank you

**Comment by klimov-paul** [comment]
Use `StorageActiveRecord` - you can specify explicit ActiveRecord class for the data storage, which can use behaviors like `TimestampBehavior`, default scopes and so on.

**Comment by sheillendra** [comment]
I've been using the `StorageActiveRecord` and `TimestampBehavior`, but why the value of `created_at` is always changing and following `updated_at` value? whereas this update process.

**Comment by klimov-paul** [comment]
Being save all old records are removed and new one inserted.

**Comment by klimov-paul** [comment]
Reconsidered as an enhancement.

**Comment by klimov-paul** [comment]
Resolved by commit 35f38528287a16ec4f8ee282e8bc9ec5f5aca767
